[build.environment]
  NODE_VERSION = "22"

[build]
  publish = ".vitepress/dist"
  command = "pnpm run build"

[[redirects]]
  from = "/llms.md"
  status = 301
  to = "/llms.txt"

[[redirects]]
  from = "/llms-full.md"
  status = 301
  to = "/llms-full.txt"
