name: 问题报告
description: 报告本站点相关的问题。请认真阅读并填写，否则 issue 将可能被直接关闭。
#title: "[Bug]: "
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        报告本站点相关的问题。请认真阅读并填写，否则 issue 将可能被直接关闭。

        本仓库是 Vue 3 文档中文翻译站 [cn.vuejs.org](https://cn.vuejs.org/)。这里仅受理以下类型的问题：
        1. 文档翻译相关；
        2. 英文文档同步相关；
        3. 其它与本仓库直接相关的问题，如译法讨论、流程优化等；

        若问题涉及文档内容以及文档中的代码块，请先确认该问题是中文仓库本身的问题，还是来自于[英文仓库](https://github.com/vuejs/docs)的问题。如果是来自英文仓库的问题，请向英文仓库提出 issue，本仓库会定期同步来自英文仓库的改动。

        下列问题**不在**本仓库的受理范围内，因此内容涉及以下类型的 issue 将可能被直接关闭：
        1. Vue 使用问题答疑；


  - type: checkboxes
    id: terms
    attributes:
      label: 提问须知
      description: 请认真阅读以上说明后，勾选本字段。
      options:
        - label: 我已阅读并知晓
          required: true

  - type: dropdown
    id: issuetype
    attributes:
      label: 问题类型
      description: 请选择本 issue 所涉及的问题类型。
      options:
        - 文档翻译相关
        - 英文文档同步相关
        - 译法讨论
        - 流程优化
        - 其它
    validations:
      required: true

  - type: textarea
    id: desc
    attributes:
      label: 问题描述
      description: 请描述你所遇到的问题，如果存在复现路径请一并描述。
    validations:
      required: true

