name: Auto Sync

on:
  schedule:
    - cron: '0 0 * * *' # At 00:00.  https://crontab.guru/
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.UPSTREAM_SYNC_TOKEN }}
          upstream_repository: vuejs/docs
          upstream_branch: main
          target_repository: vuejs-translations/docs-zh-cn
          target_branch: upstream
          force: false
          tags: false
